server:
  port: 8089
spring:
  application:
    name: eureka-server

    profiles:
      active: replica1
eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: false   #指定是否从注册中心获取服务，服务端不需要，设置成false
    register-with-eureka: false  #是否注册到注册中心，不需要
  server:

    enable-self-preservation: false #关闭保护模式
